# steps:
#   # Install dependencies
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mita','--build-arg', '_POS_USER=$_POS_USER','--build-arg', '_POS_PASS=$_POS_PASS','--build-arg', '_FLUKE_UID=$_FLUKE_UID','--build-arg', '_ACCESS_TOKEN=$_ACCESS_TOKEN', '--build-arg', '_SCRIPT_TAG=$_SCRIPT_TAG', '--build-arg', '_FS_CLI_ID=$_FS_CLI_ID',  '--build-arg', '_FS_KEY_ID=$_FS_KEY_ID', '.' ]

# images:
# - 'gcr.io/$PROJECT_ID/mita'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '--rm', 'gcr.io/line-bot-firebear-sothorn-aqve/mita@sha256:01c261ccf0cb15df6db5bbda0be0ae4a56520b6d4aa43cd1e496c71d5264278c', 'bash', 'python -m robot -i $_SCRIPT_TAG Scripts.robot']
