steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
        'run', 'gcr.io/$PROJECT_ID/mita:$SHORT_SHA', 'robot',
        '-v', 'IS_LOCAL:$_IS_LOCAL',
        '-v', 'INPUT_DATE:$_DATE',
        '-i', '$_SCRIPT_TAG', 'Script.robot'
        ]
  timeout: 3 mins
  
