POS_USER: firebear.sothorn@gmail.com
POS_PASS: Makham@home1
LINE_FLUKE_UID: Ue1db4c959e5938f9e1d658c1f2b5fcd2
LINE_ACCESS_TOKEN: Bearer TmLRfyXZ5lKKDHVJwemH4yB828m8yamE4fy+i+ROF9kCJvHlla1s9GSVcS0jqk/9v4tbygRrO3sXTCOk2dnwpmgzgRcB/xfLs4LSG968JDTTEUtAiiUx9ag1xs/O2/+amtuXT+ds36LcUt8c2ugpPQdB04t89/1O/w1cDnyilFU=
